// forget password
const BEFORE_BROWSE='BEFORE_BROWSE';
const BROWSE='BROWSE';
const AFTER_BROWSE='AFTER_BROWSE';
const BROWSE_COMPLETED ='BROWSE_COMPLETED';
const BROWSE_ERROR='BROWSE_ERROR';

export {
    // forget password
    BEFORE_BROWSE,
    BROWSE, 
    AFTER_BROWSE,
    BROWSE_COMPLETED ,
    BROWSE_ERROR
};

