// forget password
const BEFORE_FORGETPWD='BEFORE_FORGETPWD';
const FORGETPWD='FORGETPWD';
const AFTER_FORGETPWD='AFTER_FORGETPWD';
const FORGETPWD_COMPLETED ='FORGETPWD_COMPLETED';
const FORGETPWD_ERROR='FORGETPWD_ERROR';

export {
    // forget password
    BEFORE_FORGETPWD,
    FORGETPWD, 
    AFTER_FORGETPWD,
    FORGETPWD_COMPLETED ,
    FORGETPWD_ERROR
};

