// BROWSE
const BROWSE_ERROR = 'BROWSE_ERROR';
const BEFORE_BROWSE = 'BEFORE_BROWSE';
const BROWSE = 'BROWSE';
const AFTER_BROWSE = 'AFTER_BROWSE';

const BROWSE_COMPLETED='BROWSE_COMPLETED';

const SETTING = "SETTING"
const NOTIFICATION="NOTIFICATION"
const REPORT="REPORT"


const DELETE = "DELETE"
const UPDATE = "UPDATE"

export {
    //BROWSE
    BROWSE_ERROR,
    BEFORE_BROWSE,
    BROWSE,
    AFTER_BROWSE,
    BROWSE_COMPLETED,
    SETTING,
    NOTIFICATION,
    REPORT,
    DELETE,
    UPDATE
};