// login
const LOGIN_ERROR = 'LOGIN_ERROR';
const BEFORE_LOGIN = 'BEFORE_LOGIN';
const LOGIN = 'LOGIN';
const AFTER_LOGIN = 'AFTER_LOGIN';
const EMAIL_CHANGED = 'EMAIL_CHANGED';
const PWD_CHANGED = 'PWD_CHANGED';

const LOGIN_COMPLETED='LOGIN_COMPLETED';



export {
    //signup
    EMAIL_CHANGED,
    PWD_CHANGED,
    LOGIN_ERROR,
    BEFORE_LOGIN,
    LOGIN,
    AFTER_LOGIN,
    LOGIN_COMPLETED
};