
// navigate
const NAVIGATE_ERROR = 'NAVIGATE_ERROR';
const BEFORE_NAVIGATE = 'BEFBEFORE_NAVIGATEORE_LOGIN';
const NAVIGATE = 'NAVIGATE';
const NAVIGATE_COMPLETED='NAVIGATE_COMPLETED';
const NAVIGATE_SUCCES = "NAVIGATE_SUCCES";

export {
    //navigate
    NAVIGATE_ERROR,
    BEFORE_NAVIGATE,
    NAVIGATE,
    NAVIGATE_SUCCES,
    NAVIGATE_COMPLETED
};