const SIGNUP_ERROR = 'SIGNUP_ERROR';
const BEFORE_SIGNUP = 'BEFORE_SIGNUP';
const SIGNUP = 'SIGNUP';
const AFTER_SIGNUP = 'AFTER_SIGNUP';
const SIGNUP_COMPLETED='SIGNUP_COMPLETED'

const EMAIL_CHANGED = 'EMAIL_CHANGED';
const PWD_CHANGED = 'PWD_CHANGED';


const FNAME_CHANGED = 'FNAME_CHANGED';
const SNAME_CHANGED = 'SNAME_CHANGED';

export {
    EMAIL_CHANGED,
    FNAME_CHANGED,
    SNAME_CHANGED,
    PWD_CHANGED,
    SIGNUP_ERROR,
    BEFORE_SIGNUP,
    SIGNUP,
    AFTER_SIGNUP,
    SIGNUP_COMPLETED
};